const es = {
  'january': 'Enero',
  'february': 'Febrero',
  'march': 'Marzo',
  'april': 'Abril',
  'maylong': 'Mayo',
  'june': 'Junio',
  'july': 'Julio',
  'august': 'Agosto',
  'september': 'Septiembre',
  'october': 'Octubre',
  'november': 'Noviembre',
  'december': 'Diciembre',
  'jan': 'Ene',
  'feb': 'Feb',
  'mar': 'Mar',
  'apr': 'Abr',
  'may': 'May',
  'jun': 'Jun',
  'jul': 'Jul',
  'aug': 'Ago',
  'sep': 'Sep',
  'oct': 'Oct',
  'nov': 'Nov',
  'dec': 'Dic',
  'sunday': 'Domingo',
  'monday': 'Lunes',
  'tuesday': 'Martes',
  'wednesday': 'Miércoles',
  'thursday': 'Jueves',
  'friday': 'Viernes',
  'saturday': 'Sábado',
  'sun': '	Dom',
  'mon': '	Lun',
  'tue': '	Mar',
  'wed': '	Mie',
  'thu': '	Jue',
  'fri': '	Vie',
  'sat': '	Sab',
  'resource': 'Recurso',
  'duration': 'Duración',
  'comp': '% Completado',
  'completion': 'Terminado',
  'startdate': 'Inicio',
  'enddate': 'Fin',
  'moreinfo': '+información',
  'notes': 'Notas',
  'format': 'Formato',
  'hour': 'Hora',
  'day': 'Dia',
  'week': 'Semana',
  'month': 'Mes',
  'quarter': 'Trimestre',
  'hours': 'Horas',
  'days': 'Días',
  'weeks': 'Semanas',
  'months': 'Meses',
  'quarters': 'Trimestres',
  'hr': 'Hr',
  'dy': 'D',
  'wk': 'Sem',
  'mth': 'Mes',
  'qtr': 'Trim',
  'hrs': 'Hrs',
  'dys': 'Dias',
  'wks': 'Sems',
  'mths': 'Meses',
  'qtrs': 'Trims'
};

const en =
{
  'format': 'Format',
  'hour': 'Hour',
  'day': 'Day',
  'week': 'Week',
  'month': 'Month',
  'quarter': 'Quarter',
  'hours': 'Hours',
  'days': 'Days',
  'weeks': 'Weeks',
  'months': 'Months',
  'quarters': 'Quarters',
  'hr': 'Hr',
  'dy': 'Day',
  'wk': 'Wk',
  'mth': 'Mth',
  'qtr': 'Qtr',
  'hrs': 'Hrs',
  'dys': 'Days',
  'wks': 'Wks',
  'mths': 'Mths',
  'qtrs': 'Qtrs',
  'resource': 'Resource',
  'duration': 'Duration',
  'comp': '% Comp.',
  'completion': 'Completion',
  'startdate': 'Start Date',
  'enddate': 'End Date',
  'moreinfo': 'More Information',
  'notes': 'Notes',
  'january': 'January',
  'february': 'February',
  'march': 'March',
  'april': 'April',
  'maylong': 'May',
  'june': 'June',
  'july': 'July',
  'august': 'August',
  'september': 'September',
  'october': 'October',
  'november': 'November',
  'december': 'December',
  'jan': 'Jan',
  'feb': 'Feb',
  'mar': 'Mar',
  'apr': 'Apr',
  'may': 'May',
  'jun': 'Jun',
  'jul': 'Jul',
  'aug': 'Aug',
  'sep': 'Sep',
  'oct': 'Oct',
  'nov': 'Nov',

  'dec': 'Dec',
  'sunday': 'Sunday',
  'monday': 'Monday',
  'tuesday': 'Tuesday',
  'wednesday': 'Wednesday',
  'thursday': 'Thursday',

  'friday': 'Friday',
  'saturday': 'Saturday',
  'sun': 'Sun',
  'mon': 'Mon',
  'tue': 'Tue',
  'wed': 'Wed',
  'thu': 'Thu',
  'fri': 'Fri',
  'sat': 'Sat'
}

export { en, es }